---
- hosts: k8s-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults}
    - { role: bootstrap-os}
    - { role: kubernetes/preinstall, tags: preinstall }
    - { role: weavescope, tags: weavescope }

