- name: WeaveScope | copy yaml
  template:
    src: weave_scope.j2
    dest: "{{ kube_config_dir }}/weave_scope.yml"
    force: true
    owner: root
    mode: 0755
  when: inventory_hostname == groups['kube-master'][0]

- name: WeaveScope | install weavescope
  command: "{{ bin_dir }}/kubectl apply --namespace weave -f {{ kube_config_dir }}/weave_scope.yml"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: yes

